name: Daily Brief

on:
  # Every day at 07:00 UTC
  schedule:
    - cron: '0 7 * * *'
  # Manual trigger button in the Actions tab
  workflow_dispatch:

jobs:
  run-brief:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r "Retrieval Augmented Generation/Portfolio News Updater/automation_scripts/requirements.txt"

      - name: Run the news-brief script
        env:
          GMAIL_EMAIL:        ${{ secrets.GMAIL_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TO_EMAIL:           ${{ secrets.TO_EMAIL }}
          OPENAI_API_KEY:     ${{ secrets.OPENAI_API_KEY }}
          PORTFOLIO:          ${{ secrets.PORTFOLIO }}
        run: |
          python "Retrieval Augmented Generation/Portfolio News Updater/automation_scripts/daily_news_brief.py"